using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace ArcheCore.Editor
{
    public class NpcSpawnerExporter : EditorWindow
    {
        private string _patchName = "008_npc_spawners";
        private string _serverPatchDir = "";
        private Vector2 _scroll;
        private List<string> _log = new();

        [MenuItem("ArcheCore/NPC Spawner Exporter")]
        public static void Open()
        {
            GetWindow<NpcSpawnerExporter>("NPC Spawner Exporter");
        }

        private void OnEnable()
        {
            _serverPatchDir = Path.GetFullPath(
                Path.Combine(Application.dataPath,
                "../../ArcheCore/src/ArcheCore.Server.World/SQL/patches"));
        }

        private void OnGUI()
        {
            GUILayout.Label("NPC Spawner Exporter", EditorStyles.boldLabel);
            EditorGUILayout.Space();

            _patchName = EditorGUILayout.TextField("Patch Name", _patchName);
            EditorGUILayout.Space();

            GUILayout.Label("Server Patch Dir", EditorStyles.miniBoldLabel);
            EditorGUILayout.BeginHorizontal();
            _serverPatchDir = EditorGUILayout.TextField(_serverPatchDir);
            if (GUILayout.Button("...", GUILayout.Width(30)))
                _serverPatchDir = EditorUtility.OpenFolderPanel("Server Patch Dir", _serverPatchDir, "");
            EditorGUILayout.EndHorizontal();

            EditorGUILayout.Space();

            // Preview
            var markers = FindNpcMarkers();
            EditorGUILayout.HelpBox(
                $"Found {markers.Count} NPC marker(s) in scene tagged 'NpcSpawner'",
                markers.Count > 0 ? MessageType.Info : MessageType.Warning);

            // Show preview table
            if (markers.Count > 0)
            {
                EditorGUILayout.Space();
                GUILayout.Label("Preview", EditorStyles.boldLabel);
                foreach (var m in markers)
                {
                    var marker = m.GetComponent<NpcSpawnerMarker>();
                    if (marker == null) continue;
                    EditorGUILayout.LabelField(
                        $"  [{marker.TemplateId}] {marker.NpcName} x{marker.Count} " +
                        $"r={marker.Radius} @ ({m.transform.position.x:F1}, {m.transform.position.y:F1}, {m.transform.position.z:F1})",
                        EditorStyles.miniLabel);
                }
            }

            EditorGUILayout.Space();

            GUI.enabled = markers.Count > 0 && !string.IsNullOrEmpty(_patchName);
            if (GUILayout.Button("Export SQL Patch", GUILayout.Height(35)))
                Export(markers);
            GUI.enabled = true;

            // Delete after export button
            if (markers.Count > 0)
            {
                EditorGUILayout.Space();
                GUI.color = new Color(1f, 0.4f, 0.4f);
                if (GUILayout.Button("Export + Delete Markers From Scene", GUILayout.Height(35)))
                {
                    Export(markers);
                    DeleteMarkers(markers);
                }
                GUI.color = Color.white;
            }

            EditorGUILayout.Space();
            GUILayout.Label("Log", EditorStyles.boldLabel);
            _scroll = EditorGUILayout.BeginScrollView(_scroll, GUILayout.Height(150));
            foreach (var line in _log)
                GUILayout.Label(line, EditorStyles.miniLabel);
            EditorGUILayout.EndScrollView();
        }

        private List<GameObject> FindNpcMarkers()
        {
            var result = new List<GameObject>();
            foreach (var obj in FindObjectsByType<GameObject>(FindObjectsSortMode.None))
                if (obj.CompareTag("NpcSpawner"))
                    result.Add(obj);
            return result;
        }

        private void Export(List<GameObject> markers)
        {
            _log.Clear();
            var sql = BuildSql(markers);
            var fileName = $"{_patchName}.sql";
            WriteFile(_serverPatchDir, fileName, sql);
            AssetDatabase.Refresh();
            _log.Add($"✓ Exported {markers.Count} NPC spawner(s) to {fileName}");
        }

        private void DeleteMarkers(List<GameObject> markers)
        {
            foreach (var obj in markers)
            {
                _log.Add($"  🗑 Deleted {obj.name}");
                DestroyImmediate(obj);
            }
            _log.Add("✓ All markers removed from scene");
        }

        private string BuildSql(List<GameObject> markers)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Auto-generated by ArcheCore NPC Spawner Exporter");
            sb.AppendLine($"-- Scene: {SceneManager.GetActiveScene().name}");
            sb.AppendLine($"-- Date: {System.DateTime.Now:yyyy-MM-dd HH:mm}");
            sb.AppendLine();

            foreach (var obj in markers)
            {
                var marker = obj.GetComponent<NpcSpawnerMarker>();
                if (marker == null)
                {
                    _log.Add($"  ⚠ '{obj.name}' has no NpcSpawnerMarker component — skipped");
                    continue;
                }

                var pos = obj.transform.position;

                sb.AppendLine($"-- {marker.NpcName} x{marker.Count} (Template {marker.TemplateId})");
                sb.AppendLine(
                    $"INSERT INTO \"NpcSpawners\" (TemplateId, X, Y, Z, Count, Radius) VALUES " +
                    $"({marker.TemplateId}, {pos.x:F4}, {pos.y:F4}, {pos.z:F4}, {marker.Count}, {marker.Radius:F1});");
                sb.AppendLine();

                _log.Add($"  → [{marker.TemplateId}] {marker.NpcName} x{marker.Count} at ({pos.x:F1}, {pos.y:F1}, {pos.z:F1})");
            }

            return sb.ToString();
        }

        private void WriteFile(string dir, string fileName, string content)
        {
            if (string.IsNullOrEmpty(dir))
            {
                _log.Add("✗ Skipped — server patch directory not set");
                return;
            }

            Directory.CreateDirectory(dir);
            var path = Path.Combine(dir, fileName);
            File.WriteAllText(path, content);
            _log.Add($"✓ Written → {path}");
        }
    }
}